---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# image will be published to ghcr.io/<user>/<name>
name: bazzite-atty
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: stable

modules:
  - type: bling
    install:
      - 1password

  - type: dnf
    repos:
      cleanup: true
      copr:
        - solopasha/hyprland
        - avengemedia/dms
        - scrollwm/packages
      files:
        - https://raw.githubusercontent.com/atty303/howdy-rpm/refs/heads/main/howdy.repo
    install:
      packages:
        - greetd
        - greetd-selinux
        # howdy-rpm
        - howdy
        - howdy-selinux
        # solopasha/hyprland
        - uwsm
        # scrollwm/packages
        - scroll
        # avengemedia/dms
        - niri
        - dms
        - dms-greeter
        - ghostty

  - type: files
    files:
      - source: system
        destination: /

#  - type: systemd
#    system:
#      disabled:
#        - sddm.service
#      enabled:
#        - greetd.service

  - type: default-flatpaks
    configurations:
      - scope: user

  - type: signing
