---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-atty
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: bling
    install:
      - 1password

  - type: dnf
    repos:
      cleanup: true
      copr:
        - principis/howdy-beta
    install:
      packages:
#        - https://kojipkgs.fedoraproject.org//packages/dlib/19.24.8/3.fc43/x86_64/dlib-19.24.8-3.fc43.x86_64.rpm
#        - https://kojipkgs.fedoraproject.org//packages/dlib/19.24.8/3.fc43/x86_64/dlib-devel-19.24.8-3.fc43.x86_64.rpm
#        - https://kojipkgs.fedoraproject.org//packages/dlib/19.24.8/3.fc43/x86_64/python3-dlib-19.24.8-3.fc43.x86_64.rpm
        - howdy
        - howdy-gtk

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: default-flatpaks
    configurations:
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
